"""revert to case sensitive username

Revision ID: ba7bf6c5f303
Revises: 0967a4fb6032
Create Date: 2025-11-10 18:06:45.708604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba7bf6c5f303'
down_revision: Union[str, Sequence[str], None] = '0967a4fb6032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_user_username_lower'), table_name='app_user')
    op.create_unique_constraint(op.f('uq_app_user_username'), 'app_user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_app_user_username'), 'app_user', type_='unique')
    op.create_index(op.f('uq_user_username_lower'), 'app_user', [sa.literal_column('lower(username::text)')], unique=True)
    # ### end Alembic commands ###
